services:
  # NGINX API Gateway
  api_gateway:
    image: nginx:latest
    container_name: api_gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your custom NGINX config
    ports:
      - "80:80"  # Expose the API Gateway on port 80
    depends_on:
      - auth_service  # Add other services here as needed


  # Authentication service (Flask app)
  auth_service:
    build:
      context: ./auth_service
    container_name: auth_service
    ports:
      - "5000:5000"  # Expose Flask app on port 5000
    environment:
      - DATABASE_URL=postgresql://auth_user:password123@db:5432/library_auth_db
    depends_on:
      - db  # Ensure db starts before auth_service

  # PostgreSQL service
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: library_auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432

# Volumes to persist data
volumes:
  postgres_data:

# Define a custom network
networks:
  app_network:
    driver: bridge