services:

  # Authentication service (Flask app)
  auth_service:
    build:
      context: ./auth_service
    container_name: auth_service
    ports:
      - "5000:5000"  # Expose Flask app on port 5000
    environment:
      - DATABASE_URL=postgresql://auth_user:password123@auth_db:5432/library_auth_db
    depends_on:
      - auth_db

  book_service:
    build:
      context: ./book_service
    container_name: book_service
    ports:
      - "5001:5000"  # Book Service accessible on port 5001
    environment:
      - DATABASE_URL=postgresql://book_user:password123@book_db:5432/library_book_db
    depends_on:
      - book_db

  user_service:
    build:
      context: ./user_service
    container_name: user_service
    ports:
      - "5002:5000"
    environment:
      - DATABASE_URL=postgresql://user_user:password123@user_db:5432/library_user_db
    depends_on:
      - user_db

  # NGINX API Gateway
  api_gateway:
    image: nginx:latest
    container_name: api_gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your custom NGINX config
    ports:
      - "80:80"  # Expose the API Gateway on port 80
    depends_on:
      - auth_service
      - book_service
      - user_service

  # PostgreSQL service
  auth_db:
    image: postgres:13
    container_name: auth_db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: library_auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Expose PostgreSQL on port 5432

  book_db:
    image: postgres:13
    container_name: book_db
    environment:
      POSTGRES_USER: book_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: library_book_db
    volumes:
      - book_db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"  # Expose PostgreSQL on port 5432

  user_db:
    image: postgres:13
    container_name: user_db
    environment:
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: library_user_db
    volumes:
      - user_db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"  # Expose PostgreSQL on port 5432


# Volumes to persist data
volumes:
  auth_db_data:
  book_db_data:
  user_db_data:

# Define a custom network
networks:
  app_network:
    driver: bridge